const dataKey='wander-wallet-expenses',baseKey='wander-wallet-base-currency',legacyKey='wander-wallet-currency',rateCacheKey='wander-wallet-rate-cache',budgetKey='wander-wallet-budget',customCategoryKey='wander-wallet-custom-categories',categoryOrderKey='wander-wallet-category-order',tagKey='wander-wallet-category-tags',tagColorKey='wander-wallet-tag-colors',onboardingKey='wander-wallet-onboarding-complete',travelCurrencyKey='wander-wallet-travel-currency';

const symbols={KRW:'₩',USD:'$',EUR:'€',GBP:'£',JPY:'¥'},colors=['#ed7248','#f5bc48','#8fc6b1','#92b5d5','#b8a5d4','#b4aca0'],icons={식비:'☕',교통:'◈',생활:'⌂',여행:'✦',학업:'✎',기타:'○'},defaultCategories=['식비','교통','생활','여행','학업','기타'];

let baseCurrency=localStorage.getItem(baseKey)||localStorage.getItem(legacyKey)||'',travelCurrency=localStorage.getItem(travelCurrencyKey)||baseCurrency||'EUR';
let selectedMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);

const readStoredJson=(key,fallback)=>{try{const value=localStorage.getItem(key);return value===null?fallback:JSON.parse(value)}catch{return fallback}},readStoredArray=key=>{const value=readStoredJson(key,[]);return Array.isArray(value)?value:[]},readStoredObject=key=>{const value=readStoredJson(key,{});return value&&typeof value==='object'&&!Array.isArray(value)?value:{}};
let expenses=readStoredArray(dataKey).filter(item=>item&&typeof item==='object'),rates=null,rateDate='',budget=Number(localStorage.getItem(budgetKey))||0,customCategories=readStoredArray(customCategoryKey).filter(item=>typeof item==='string'),categoryOrder=readStoredArray(categoryOrderKey).filter(item=>typeof item==='string'),categoryTags=readStoredObject(tagKey),tagColors=readStoredObject(tagColorKey),exchangeRequestId=0,pendingExpense=null,editingTag=null;
if(!categoryOrder.length)categoryOrder=[...defaultCategories,...customCategories];

expenses=expenses.map(x=>({...(x.baseAmount===undefined?{...x,inputAmount:x.amount,inputCurrency:baseCurrency||'KRW',baseAmount:x.amount}:x),categories:x.categories||[x.category||'식비'],tags:x.tags||[],createdAt:x.createdAt||new Date().toISOString()}));

const today=new Date(),money=(x,c=baseCurrency)=>new Intl.NumberFormat('ko-KR',{minimumFractionDigits:0,maximumFractionDigits:['EUR','USD','GBP'].includes(c)?2:0}).format(x),format=x=>`${symbols[baseCurrency]||''}${money(x)}`,formatBudget=x=>`${symbols[baseCurrency]||''}${new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0}).format(Math.round(x))}`,allCategories=()=>categoryOrder;

const save=()=>localStorage.setItem(dataKey,JSON.stringify(expenses));

const expenseDate=document.querySelector('#expenseDate'),toDateValue=date=>date.toISOString().slice(0,10);
expenseDate.value=toDateValue(today);
document.querySelector('#inputCurrency').value=travelCurrency;
function syncExpenseDate(){const date=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth(),Math.min(today.getDate(),new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1,0).getDate()));expenseDate.value=toDateValue(date)}
function renderMonthLabel(){document.querySelector('#monthLabel').textContent=`${selectedMonth.getFullYear()}년 ${selectedMonth.getMonth()+1}월`}
renderMonthLabel();
document.querySelector('#prevMonth').onclick=()=>{selectedMonth.setMonth(selectedMonth.getMonth()-1);syncExpenseDate();renderMonthLabel();render()};
document.querySelector('#nextMonth').onclick=()=>{selectedMonth.setMonth(selectedMonth.getMonth()+1);syncExpenseDate();renderMonthLabel();render()};
expenseDate.onchange=()=>{const date=new Date(`${expenseDate.value}T12:00:00`);if(Number.isNaN(date.getTime()))return;selectedMonth=new Date(date.getFullYear(),date.getMonth(),1);renderMonthLabel();render()};

function restoreCachedRates(){const cache=JSON.parse(localStorage.getItem(rateCacheKey)||'null');
if(cache?.base===baseCurrency&&cache.rates){rates=cache.rates;
rateDate=cache.date;
return true}rates=null;
rateDate='';
return false}
function fetchWithTimeout(url,timeout=2500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
return fetch(url,{signal:controller.signal,cache:'no-store'}).then(r=>{if(!r.ok)throw Error();
return r.json()}).finally(()=>clearTimeout(timer))}
function loadRates(){if(!baseCurrency)return;
restoreCachedRates();
const currencies=['KRW','USD','EUR','GBP','JPY'].filter(currency=>currency!==baseCurrency),live=Promise.all(currencies.map(currency=>fetchWithTimeout(`https://www.currencyexchangetool.com/api/v1/convert?amount=1&from=${baseCurrency}&to=${currency}&_=${Date.now()}`,5000).then(data=>{const rate=Number(data.rate);if(!data.success||!Number.isFinite(rate))throw Error();return [currency,rate]}))).then(entries=>({rates:{[baseCurrency]:1,...Object.fromEntries(entries)},date:'실시간'})),list='KRW,USD,EUR,GBP,JPY',a=fetchWithTimeout(`https://api.frankfurter.dev/v1/latest?base=${baseCurrency}&symbols=${list}`).then(d=>({rates:{...d.rates,[baseCurrency]:1},date:d.date})),b=fetchWithTimeout(`https://open.er-api.com/v6/latest/${baseCurrency}`).then(d=>({rates:{KRW:d.rates.KRW,USD:d.rates.USD,EUR:d.rates.EUR,GBP:d.rates.GBP,JPY:d.rates.JPY,[baseCurrency]:1},date:new Date(d.time_last_update_unix*1000).toISOString().slice(0,10)}));
return live.catch(()=>Promise.any([a,b])).then(r=>{rates=r.rates;
rateDate=r.date;
localStorage.setItem(rateCacheKey,JSON.stringify({base:baseCurrency,rates,date:rateDate}));
render()}).catch(()=>note(rates?'':'환율 조회가 지연되고 있어요.'))}
function convert(amount,input){const x=input===baseCurrency?amount:rates?.[input]?amount/rates[input]:null;
return x===null?null:['EUR','USD','GBP'].includes(baseCurrency)?Math.round((x+Number.EPSILON)*100)/100:Math.round(x)}
function roundBase(x){return ['EUR','USD','GBP'].includes(baseCurrency)?Math.round((x+Number.EPSILON)*100)/100:Math.round(x)}
function unitToKrwRate(input){if(!rates)return null;if(input==='KRW')return 1;if(baseCurrency==='KRW')return rates[input]?1/rates[input]:null;if(input===baseCurrency)return rates.KRW??null;return rates.KRW&&rates[input]?rates.KRW/rates[input]:null}
function note(error=''){const input=document.querySelector('#inputCurrency').value,el=document.querySelector('#conversionNote');if(!el)return;const krwRate=unitToKrwRate(input);el.textContent=error||krwRate===null?'실시간 환율을 불러오는 중이에요…':`${symbols[input]}1 = ₩${money(Math.round(krwRate),'KRW')} · ${rateDate==='실시간'?'실시간 환율':`${rateDate} 기준 환율`}`}
function exchangeTimestamp(value){const parts=new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Seoul'}).formatToParts(new Date(value)),part=type=>parts.find(x=>x.type===type)?.value;return `${part('month')}.${part('day')} ${part('hour')}:${part('minute')}`}
async function loadExchangeGraph(){const from=document.querySelector('#graphBase').value,to=document.querySelector('#graphQuote').value,value=document.querySelector('#exchangeRateValue'),svg=document.querySelector('#exchangeChart'),requestId=++exchangeRequestId;if(from===to){value.textContent=`1 ${from} = 1 ${to}`;document.querySelector('#exchangeRateDate').textContent='실시간 갱신';svg.innerHTML='<path class="chart-line" d="M 5 52 L 325 52" />';return}value.textContent='환율 불러오는 중…';const end=new Date(),start=new Date(end);start.setDate(end.getDate()-30),date=x=>x.toISOString().slice(0,10),historyUrl=`https://api.frankfurter.dev/v1/${date(start)}..${date(end)}?base=${from}&symbols=${to}`,liveUrl=`https://www.currencyexchangetool.com/api/v1/convert?amount=1&from=${from}&to=${to}&_=${Date.now()}`;const [historyResult,liveResult]=await Promise.allSettled([fetchWithTimeout(historyUrl,5000),fetchWithTimeout(liveUrl,5000)]);if(requestId!==exchangeRequestId)return;try{if(historyResult.status!=='fulfilled')throw Error();const entries=Object.entries(historyResult.value.rates).map(([day,rate])=>({day,value:rate[to],time:new Date(`${day}T12:00:00Z`).getTime()})).filter(x=>Number.isFinite(x.value));if(!entries.length)throw Error();const live=liveResult.status==='fulfilled'&&liveResult.value?.success&&Number.isFinite(Number(liveResult.value.rate))?{value:Number(liveResult.value.rate),time:new Date(liveResult.value.updatedAt||Date.now()).getTime()}:null;if(live)entries.push({day:'오늘',...live});const values=entries.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),range=max-min||1,firstTime=entries[0].time,lastTime=entries.at(-1).time,timeRange=lastTime-firstTime||1,points=entries.map(x=>{const px=8+(x.time-firstTime)/timeRange*314,py=91-(x.value-min)/range*76;return [px,py]}),line=points.map((p,i)=>`${i?'L':'M'} ${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' '),area=`M ${points[0][0]} 97 ${points.map(p=>`L ${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' ')} L ${points.at(-1)[0]} 97 Z`,latest=entries.at(-1);value.textContent=`1 ${from} = ${money(latest.value,to)} ${to}`;document.querySelector('#exchangeRateDate').textContent=live?`실시간 갱신 · ${exchangeTimestamp(live.time)}`:`${latest.day} 기준 · 최근 30일`;document.querySelector('#chartStartDate').textContent=entries[0].day.slice(5).replace('-','.');document.querySelector('#chartEndDate').textContent=live?`오늘 ${exchangeTimestamp(live.time).split(' ')[1]}`:latest.day.slice(5).replace('-','.');svg.innerHTML=`<path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/><circle class="chart-dot" cx="${points.at(-1)[0]}" cy="${points.at(-1)[1]}" r="3.5"/>`}catch{value.textContent='환율을 불러오지 못했어요';document.querySelector('#exchangeRateDate').textContent='잠시 후 다시 시도해 주세요.';svg.innerHTML=''}}
function esc(x){return x.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function tagsFor(categories){return [...new Set(categories.flatMap(category=>categoryTags[category]||[]))]}
function tagColor(tag,categories=[]){const color=categories.map(category=>tagColors[category]?.[tag]).find(Boolean)||'#ed7248';return /^#[0-9a-f]{6}$/i.test(color)?color:'#ed7248'}
function renderTagOptions(id,name,categories,selected=[]){const tags=tagsFor(categories),el=document.querySelector(id);el.innerHTML=tags.map(tag=>`<label class="tag-option"><input type="checkbox" name="${name}" value="${esc(tag)}" ${selected.includes(tag)?'checked':''}><span style="--tag-color:${tagColor(tag,categories)}">#${esc(tag)}</span></label>`).join('')}
function selectedCategories(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value)}
function renderExpenseTags(selected=[]){renderTagOptions('#expenseTagOptions','expenseTag',selectedCategories('expenseCategory'),selected)}
function renderEditTags(selected=[]){renderTagOptions('#editTagOptions','editExpenseTag',selectedCategories('editExpenseCategory'),selected)}
function tagGroups(items,category){const groups=new Map();items.filter(item=>item.categories.includes(category)).forEach(item=>{const tags=(item.tags||[]).filter(tag=>(categoryTags[category]||[]).includes(tag));tags.forEach(tag=>{const current=groups.get(tag)||{name:tag,color:tagColor(tag,[category]),value:0};current.value+=item.baseAmount/item.categories.length/tags.length;groups.set(tag,current)})});return [...groups.values()].filter(group=>group.value).sort((a,b)=>b.value-a.value)}
function categoryTagDonut(groups){const total=groups.reduce((sum,group)=>sum+group.value,0);let progress=0,labels=[],gradient=groups.map(group=>{const start=progress,percent=Math.round(group.value/total*100),mid=(start+percent/2)/100*Math.PI*2-Math.PI/2;progress+=group.value/total*100;labels.push(`<b class="tag-donut-percent" style="left:${(50+Math.cos(mid)*37).toFixed(1)}%;top:${(50+Math.sin(mid)*37).toFixed(1)}%">${percent}%</b>`);return `${group.color} ${start}% ${progress}%`}).join(',');return `<div class="tag-donut-chart"><div class="tag-donut" style="background:conic-gradient(${gradient})">${labels.join('')}</div><div class="tag-donut-legend">${groups.map(group=>`<div><span><i style="background:${group.color}"></i>${esc(group.name)}</span><strong>${format(group.value)}</strong></div>`).join('')}</div></div>`}
function renderCategoryTagDonuts(id,items){const charts=allCategories().map(category=>({category,groups:tagGroups(items,category)})).filter(chart=>chart.groups.length),el=document.querySelector(id);el.innerHTML=charts.length?`<div class="category-tag-charts">${charts.map(chart=>`<article><h4>#${esc(chart.category)} 지출</h4>${categoryTagDonut(chart.groups)}</article>`).join('')}</div>`:'<div class="empty-state">태그가 달린 지출을 추가하면 태그별 비율을 보여드려요.</div>'}
function renderCategories(){document.querySelector('#categoryOptions').innerHTML=allCategories().map(x=>`<label class="category-option" draggable="true" data-category="${esc(x)}"><input type="checkbox" name="expenseCategory" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('');renderExpenseTags()}
function renderEditCategories(selected){document.querySelector('#editCategoryOptions').innerHTML=allCategories().map(x=>`<label class="category-option"><input type="checkbox" name="editExpenseCategory" value="${esc(x)}" ${selected.includes(x)?'checked':''}><span>${esc(x)}</span></label>`).join('')}
function openEditExpense(id){const item=expenses.find(x=>x.id===Number(id));if(!item)return;document.querySelector('#editExpenseId').value=item.id;document.querySelector('#editExpenseName').value=item.name;document.querySelector('#editExpenseAmount').value=item.inputAmount;document.querySelector('#editInputCurrency').value=item.inputCurrency;document.querySelector('#editExpenseDate').value=toDateValue(new Date(item.createdAt));renderEditCategories(item.categories);renderEditTags(item.tags);document.querySelector('#editExpenseModal').hidden=false}
function render(){const monthExpenses=expenses.filter(x=>{const date=new Date(x.createdAt);return date.getFullYear()===selectedMonth.getFullYear()&&date.getMonth()===selectedMonth.getMonth()}),total=monthExpenses.reduce((s,x)=>s+x.baseAmount,0),analysisTotal=expenses.reduce((s,x)=>s+x.baseAmount,0),monthGrouped=allCategories().map((name,i)=>({name,color:colors[i%colors.length],value:monthExpenses.reduce((s,x)=>s+(x.categories.includes(name)?x.baseAmount/x.categories.length:0),0)})).filter(x=>x.value),analysisGrouped=allCategories().map((name,i)=>({name,color:colors[i%colors.length],value:expenses.reduce((s,x)=>s+(x.categories.includes(name)?x.baseAmount/x.categories.length:0),0)})).filter(x=>x.value),ranking=[...monthGrouped].sort((a,b)=>b.value-a.value),top=ranking[0],second=ranking[1],ratio=budget?Math.min(total/budget*100,100):0,daysInMonth=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1,0).getDate(),isCurrentMonth=selectedMonth.getFullYear()===today.getFullYear()&&selectedMonth.getMonth()===today.getMonth(),monthProgress=isCurrentMonth?Math.round(today.getDate()/daysInMonth*100):selectedMonth<today?100:0;
const baseCurrencyText=baseCurrency?`기준 ${baseCurrency}`:'기준 통화 설정';document.querySelector('#baseCurrencyLabel').textContent=baseCurrencyText;document.querySelector('#mobileBaseCurrencyLabel').textContent=baseCurrencyText;
document.querySelector('#totalSpend').textContent=format(total);
const totalKrw=baseCurrency==='KRW'?total:monthExpenses.length&&monthExpenses.every(item=>Number.isFinite(item.krwAmount))?monthExpenses.reduce((sum,item)=>sum+item.krwAmount,0):rates?.KRW?monthExpenses.reduce((sum,item)=>sum+(Number.isFinite(item.krwAmount)?item.krwAmount:item.baseAmount*rates.KRW),0):null,totalSpendKrw=document.querySelector('#totalSpendKrw');
totalSpendKrw.hidden=baseCurrency==='KRW';
if(baseCurrency!=='KRW')totalSpendKrw.textContent=totalKrw===null?'원화 환산 중…':`₩${money(totalKrw,'KRW')}`;
const totalSpendTravel=document.querySelector('#totalSpendTravel'),travelRate=travelCurrency==='KRW'?1:rates?.[travelCurrency],travelTotal=baseCurrency==='KRW'&&travelRate?monthExpenses.reduce((sum,item)=>sum+(item.inputCurrency===travelCurrency?item.inputAmount:Number.isFinite(item.travelAmount)?item.travelAmount:item.baseAmount*travelRate),0):null;
totalSpendTravel.hidden=baseCurrency!=='KRW';
if(baseCurrency==='KRW')totalSpendTravel.textContent=travelTotal===null?'여행 통화 환산 중…':`${symbols[travelCurrency]}${money(travelTotal,travelCurrency)}`;
document.querySelector('#chartTotal').textContent=format(analysisTotal);
document.querySelector('#budgetAmount').textContent=budget?formatBudget(budget):'예산 미설정';
document.querySelector('#budgetProgress').style.width=`${ratio}%`;
document.querySelector('#budgetStatus').textContent=budget?`예산의 ${Math.round(total/budget*100)}%를 사용했어요`:'수정 버튼으로 예산을 설정하세요';
document.querySelector('#monthStatus').textContent=`이번 달이 ${monthProgress}% 지났어요`;
document.querySelector('#monthProgress').style.width=`${monthProgress}%`;
document.querySelector('#topCategory').textContent=top?top.name:'—';
const topCategoryAmount=document.querySelector('#topCategoryAmount');topCategoryAmount.textContent=top?`${format(top.value)} 지출`:'지출을 기록해 보세요';topCategoryAmount.classList.toggle('empty-summary-copy',!top);
document.querySelector('#secondCategory').textContent=second?second.name:'—';
document.querySelector('#secondCategoryAmount').textContent=second?`${format(second.value)} 지출`:'—';
let p=0;
document.querySelector('#donut').style.background=analysisGrouped.length?`conic-gradient(${analysisGrouped.map(x=>{let a=p;
p+=x.value/analysisTotal*100;
return `${x.color} ${a}% ${p}%`}).join(',')})`:'#ebe7dd';
document.querySelector('#legend').innerHTML=analysisGrouped.length?analysisGrouped.map(x=>`<div class="legend-item"><span class="legend-left"><i class="legend-dot" style="background:${x.color}"></i>${x.name}</span><span class="legend-price">${format(x.value)}</span></div>`).join(''):'<div class="empty-state">항목 분석은 지출을 추가한 뒤 표시돼요.</div>';renderCategoryTagDonuts('#dashboardTagChart',expenses);
document.querySelector('#expenseList').innerHTML=monthExpenses.length?[...monthExpenses].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)||b.id-a.id).map(x=>`<div class="expense-item"><span class="category-icon" style="background:${colors[allCategories().indexOf(x.categories[0])%colors.length]}33">${icons[x.categories[0]]||'•'}</span><div><div class="expense-name">${esc(x.name)}</div><div class="expense-meta">${esc(x.categories.join(' · '))}${x.tags?.length?` · ${x.tags.map(tag=>`<i class="expense-tag" style="--tag-color:${tagColor(tag,x.categories)}">#${esc(tag)}</i>`).join(' ')}`:''} · ${x.date} · ${symbols[x.inputCurrency]}${money(x.inputAmount,x.inputCurrency)}</div></div><span class="expense-price">${format(x.baseAmount)}</span><button class="edit-button" data-edit-id="${x.id}" aria-label="${esc(x.name)} 수정">✎</button><button class="delete-button" data-delete-id="${x.id}" aria-label="${esc(x.name)} 삭제">×</button></div>`).join(''):'<div class="empty-state">이 달에는 아직 기록이 없어요.</div>';
const budgetGap=budget?Math.round(total/budget*100)-monthProgress:null;
const tipMessage=budgetGap===null?'예산을 설정하면 소비 속도를 비교해 드릴게요.':budgetGap<-10?'여행은 즐기고, 예산은 아끼고 있어요.<br>지금 페이스라면 이번 달도 든든해요.':Math.abs(budgetGap)<=10?'여행도 즐기고, 예산도 잘 맞춰가고 있어요.<br>지금 페이스라면 이번 달도 안정적이에요.':'여행은 충분히 즐기고 있어 남은 일정은 지출 조절이 필요해요.';document.querySelector('#tipText').innerHTML=tipMessage;document.querySelector('#mobileBudgetTip').innerHTML=tipMessage;
note()}
function openModal(mode='change'){const isInitial=mode==='initial';document.querySelector('#baseCurrencySelect').value=baseCurrency||'EUR';
document.querySelector('#travelCurrencySelect').value=travelCurrency;
const modalTitle=document.querySelector('#modalTitle');modalTitle.innerHTML=isInitial?'여행 지역과 기록 기준을<br />정해 주세요.':'통화 설정을 바꾸고 싶으신가요?';modalTitle.classList.toggle('modal-title-single-line',!isInitial);
document.querySelector('#currencyModal p').innerHTML=isInitial?'여행 지역 통화는 결제 통화의 기본값으로 설정되고,<br />모든 지출은 기준 통화로 환산되어 기록돼요.':'여행 지역 통화와 기록 기준 통화를 변경할 수 있어요.<br />기존 지출은 기존 기준 통화로 유지돼요.';
document.querySelector('#saveBaseCurrency').textContent=isInitial?'이 설정으로 시작하기':'이 설정으로 바꾸기';
document.querySelector('#baseChangeWarning').textContent='';
document.querySelector('#currencyModal').hidden=false}
document.querySelector('#settingsButton').onclick=()=>{trackMenuClick('base_currency');openModal()};
document.querySelector('#mobileSettingsButton').onclick=()=>{trackMenuClick('base_currency');openModal()};
document.querySelector('#saveBaseCurrency').onclick=()=>{baseCurrency=document.querySelector('#baseCurrencySelect').value;
travelCurrency=document.querySelector('#travelCurrencySelect').value;
localStorage.setItem(baseKey,baseCurrency);
localStorage.setItem(travelCurrencyKey,travelCurrency);
localStorage.setItem(onboardingKey,'true');
document.querySelector('#currencyModal').hidden=true;
document.querySelector('#inputCurrency').value=travelCurrency;
restoreCachedRates();
render();
loadRates();
document.querySelector('#graphBase').value=travelCurrency;
document.querySelector('#graphQuote').value='KRW';
loadExchangeGraph()};

function renderReport(){const key=document.querySelector('#reportMonthSelect').value,[year,month]=key.split('-').map(Number),items=expenses.filter(x=>{const date=new Date(x.createdAt);return date.getFullYear()===year&&date.getMonth()+1===month}),total=items.reduce((sum,x)=>sum+x.baseAmount,0),groups=allCategories().map((name,index)=>({name,color:colors[index%colors.length],value:items.reduce((sum,x)=>sum+(x.categories.includes(name)?x.baseAmount/x.categories.length:0),0)})).filter(x=>x.value).sort((a,b)=>b.value-a.value),top=groups[0],max=top?.value||1,delta=budget?total-budget:null,percent=budget?Math.round(Math.abs(delta)/budget*100):null;document.querySelector('#reportTitle').textContent=`${month}월 월간 리포트`;document.querySelector('#reportBreakdownTitle').textContent=`${month}월 항목별 지출`;document.querySelector('#reportTagsTitle').textContent=`${month}월 태그별 지출`;document.querySelector('#reportTotal').textContent=format(total);document.querySelector('#reportTopCategory').textContent=top?.name||'—';document.querySelector('#reportTopAmount').textContent=top?format(top.value):'기록이 없어요';document.querySelector('#reportBudgetDelta').textContent=delta===null?'예산 미설정':delta>0?`${percent}% 초과`:`${percent}% 절약`;document.querySelector('#reportBudgetAmount').textContent=delta===null?'예산을 설정해 주세요':delta>0?`${format(delta)} 더 썼어요`:`${format(Math.abs(delta))} 덜 썼어요`;document.querySelector('#reportCategoryList').innerHTML=groups.length?groups.map(x=>`<div class="report-category-row"><span>${esc(x.name)}</span><i style="width:${x.value/max*100}%;background:${x.color}"></i><strong>${format(x.value)}</strong></div>`).join(''):'<div class="empty-state">이 달에는 기록이 없어요.</div>';renderCategoryTagDonuts('#reportTagChart',items)}
function renderComparison(){const totals=new Map();expenses.forEach(x=>{const date=new Date(x.createdAt),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;totals.set(key,(totals.get(key)||0)+x.baseAmount)});const [year,month]=document.querySelector('#reportMonthSelect').value.split('-').map(Number),end=new Date(year,month-1,1),keys=[2,1,0].map(offset=>{const date=new Date(end.getFullYear(),end.getMonth()-offset,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}),values=keys.map(key=>totals.get(key)||0),max=Math.max(...values,1),palette=['#92b5d5','#f5bc48','#ed7248'],topIndex=values.indexOf(Math.max(...values));document.querySelector('#reportComparisonChart').innerHTML=`<div class="comparison-bars">${keys.map((key,index)=>{const [,label]=key.split('-');return `<div class="comparison-bar-item"><strong>${format(values[index])}</strong><div class="comparison-bar-track"><i style="height:${values[index]/max*100}%;background:${palette[index]}"></i></div><span>${Number(label)}월</span></div>`}).join('')}</div>`;document.querySelector('#reportComparisonNote').textContent=values.some(Boolean)?`${Number(keys[topIndex].split('-')[1])}월달 지출이 가장 많아요.`:'비교할 지출 기록이 없어요.'}
const isMobileView=()=>window.matchMedia('(max-width:720px)').matches;
const trackMenuClick=menuName=>{if(typeof window.gtag==='function')window.gtag('event','menu_click',{menu_name:menuName,screen_type:isMobileView()?'mobile':'desktop'})};
function setMobileScreen(screen){document.activeElement?.blur();document.body.dataset.mobileScreen=screen;if(screen!=='report'){document.querySelector('#reportModal').hidden=true;document.querySelector('#closeReport').textContent='×'}window.scrollTo(0,0)}
function openReport(){const select=document.querySelector('#reportMonthSelect'),keys=[...new Set(expenses.map(x=>{const date=new Date(x.createdAt);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}))],current=`${selectedMonth.getFullYear()}-${String(selectedMonth.getMonth()+1).padStart(2,'0')}`;if(!keys.includes(current))keys.push(current);select.innerHTML=keys.sort().reverse().map(x=>{const [year,month]=x.split('-');return `<option value="${x}">${year}년 ${Number(month)}월</option>`}).join('');select.value=current;renderReport();renderComparison();document.querySelector('#reportModal').hidden=false;if(isMobileView())setMobileScreen('report')}
document.querySelector('#reportButton').onclick=()=>{trackMenuClick('monthly_report');openReport()};
document.querySelector('#mobileHeaderReport').onclick=()=>{trackMenuClick('monthly_report');openReport()};
document.querySelector('#mobileExchangeButton').onclick=()=>{trackMenuClick('exchange_rate');loadExchangeGraph();setMobileScreen('exchange')};
document.querySelector('#mobileBrandHome').onclick=e=>{e.preventDefault();trackMenuClick('home');setMobileScreen('home')};
document.querySelector('#mobileHomeLink').onclick=e=>{e.preventDefault();trackMenuClick('home');setMobileScreen('home')};
document.querySelector('#mobileReportLink').onclick=e=>{e.preventDefault();trackMenuClick('monthly_report');openReport()};
document.querySelector('#mobileStoriesLink').onclick=e=>{e.preventDefault();trackMenuClick('stories');setMobileScreen('stories')};
document.querySelector('#mobileFeedbackLink').onclick=e=>{e.preventDefault();trackMenuClick('feedback');setMobileScreen('feedback')};
document.querySelector('#closeReport').onclick=()=>{document.querySelector('#reportModal').hidden=true;document.querySelector('#closeReport').textContent='×';if(isMobileView())setMobileScreen('home')};
document.querySelector('#reportMonthSelect').onchange=()=>{renderReport();renderComparison()};
document.querySelector('#mobileTagSpendLink').onclick=e=>{e.preventDefault();trackMenuClick('my_spending');renderCategoryTagDonuts('#mobileCategoryTagChart',expenses);setMobileScreen('category')};
document.querySelector('#graphBase').onchange=loadExchangeGraph;
document.querySelector('#graphQuote').onchange=loadExchangeGraph;
document.querySelector('#refreshExchange').onclick=loadExchangeGraph;

function saveBudget(){const amount=document.querySelector('#budgetAmount'),value=Number(amount.textContent.replace(/[^0-9.]/g,''));if(!value)return alert('올바른 예산 금액을 입력해 주세요.');budget=Math.round(value);localStorage.setItem(budgetKey,budget);amount.contentEditable='false';document.querySelector('#editBudget').textContent='수정';render()}
document.querySelector('#editBudget').onclick=()=>{const amount=document.querySelector('#budgetAmount');if(amount.contentEditable==='true')return saveBudget();amount.textContent=budget||'';amount.contentEditable='true';document.querySelector('#editBudget').textContent='저장';amount.focus()};
document.querySelector('#budgetAmount').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveBudget()}};

document.querySelector('#addCategory').onclick=()=>{const name=prompt('새 지출 항목 이름을 입력하세요.');
if(!name?.trim()||allCategories().includes(name.trim()))return;
customCategories.push(name.trim());
localStorage.setItem(customCategoryKey,JSON.stringify(customCategories));
categoryOrder.push(name.trim());
localStorage.setItem(categoryOrderKey,JSON.stringify(categoryOrder));
renderCategories()};
function setTagNamePlaceholder(){document.querySelector('#tagName').placeholder=document.querySelector('#tagCategorySelect').value==='식비'?'예: 외식, 마트':'태그 이름 입력'}
function setTagColor(color){document.querySelector('#tagColor').value=color;document.querySelectorAll('[data-tag-color]').forEach(button=>button.classList.toggle('selected',button.dataset.tagColor.toLowerCase()===color.toLowerCase()))}
function refreshTagViews(){renderExpenseTags([...document.querySelectorAll('input[name="expenseTag"]:checked')].map(x=>x.value));if(!document.querySelector('#editExpenseModal').hidden){const item=expenses.find(x=>x.id===Number(document.querySelector('#editExpenseId').value));renderEditTags(item?.tags||[])}if(!document.querySelector('#tagManageModal').hidden)renderTagManager()}
function renderTagManager(){const entries=allCategories().flatMap(category=>(categoryTags[category]||[]).map(tag=>({category,tag}))),list=document.querySelector('#tagManageList');list.innerHTML=entries.length?entries.map(({category,tag})=>`<div class="tag-manage-row"><span><i style="background:${tagColor(tag,[category])}"></i>${esc(category)} · #${esc(tag)}</span><button data-tag-action="edit" data-category="${esc(category)}" data-tag="${esc(tag)}" type="button">수정</button><button data-tag-action="delete" data-category="${esc(category)}" data-tag="${esc(tag)}" type="button">삭제</button></div>`).join(''):'<div class="empty-state">아직 만든 태그가 없어요.</div>'}
function openTagEditor(category='',tag=''){editingTag=tag?{category,tag}:null;document.querySelector('#tagCategorySelect').innerHTML=allCategories().map(item=>`<option value="${esc(item)}">${esc(item)}</option>`).join('');document.querySelector('#tagCategorySelect').value=category||selectedCategories('expenseCategory')[0]||allCategories()[0];document.querySelector('#tagCategorySelect').disabled=Boolean(editingTag);document.querySelector('#tagName').value=tag;setTagNamePlaceholder();setTagColor(tag?tagColor(tag,[category]):'#ed7248');document.querySelector('#tagModalTitle').textContent=tag?'태그 수정':'태그 추가';document.querySelector('#deleteTag').hidden=!tag;document.querySelector('#saveTag').textContent=tag?'태그 수정 저장':'태그 만들기';document.querySelector('#tagModal').hidden=false;document.querySelector('#tagName').focus()}
document.querySelector('#addTag').onclick=()=>openTagEditor();
document.querySelector('#tagCategorySelect').onchange=setTagNamePlaceholder;
document.querySelector('#tagColorOptions').onclick=e=>{const button=e.target.closest('[data-tag-color],#customTagColor');if(!button)return;if(button.id==='customTagColor')return document.querySelector('#tagColor').click();setTagColor(button.dataset.tagColor)};
document.querySelector('#tagColor').oninput=e=>setTagColor(e.target.value);
document.querySelector('#closeTagModal').onclick=()=>{editingTag=null;document.querySelector('#tagModal').hidden=true};
function deleteTag(category,tag){if(!confirm(`#${tag} 태그를 삭제할까요? 기존 지출에서도 제거됩니다.`))return;categoryTags={...categoryTags,[category]:(categoryTags[category]||[]).filter(item=>item!==tag)};const colors={...(tagColors[category]||{})};delete colors[tag];tagColors={...tagColors,[category]:colors};expenses=expenses.map(item=>item.categories.includes(category)?{...item,tags:item.tags.filter(itemTag=>itemTag!==tag)}:item);localStorage.setItem(tagKey,JSON.stringify(categoryTags));localStorage.setItem(tagColorKey,JSON.stringify(tagColors));save();refreshTagViews();render()}
document.querySelector('#tagForm').onsubmit=e=>{e.preventDefault();const category=document.querySelector('#tagCategorySelect').value,name=document.querySelector('#tagName').value.trim(),color=document.querySelector('#tagColor').value,wasEditing=Boolean(editingTag);if(!name)return;if(editingTag){const oldTag=editingTag.tag;if(name!==oldTag&&(categoryTags[category]||[]).includes(name))return alert('이미 추가된 태그예요.');categoryTags={...categoryTags,[category]:(categoryTags[category]||[]).map(tag=>tag===oldTag?name:tag)};const colors={...(tagColors[category]||{})};delete colors[oldTag];colors[name]=color;tagColors={...tagColors,[category]:colors};expenses=expenses.map(item=>item.categories.includes(category)?{...item,tags:item.tags.map(tag=>tag===oldTag?name:tag)}:item);save()}else{if((categoryTags[category]||[]).includes(name))return alert('이미 추가된 태그예요.');categoryTags={...categoryTags,[category]:[...(categoryTags[category]||[]),name]};tagColors={...tagColors,[category]:{...(tagColors[category]||{}),[name]:color}};const selected=selectedCategories('expenseCategory');if(!selected.includes(category))document.querySelector(`input[name="expenseCategory"][value="${CSS.escape(category)}"]`).checked=true}localStorage.setItem(tagKey,JSON.stringify(categoryTags));localStorage.setItem(tagColorKey,JSON.stringify(tagColors));editingTag=null;document.querySelector('#tagModal').hidden=true;if(wasEditing)refreshTagViews();else{renderExpenseTags([...document.querySelectorAll('input[name="expenseTag"]:checked')].map(x=>x.value).concat(name));if(!document.querySelector('#editExpenseModal').hidden){const item=expenses.find(x=>x.id===Number(document.querySelector('#editExpenseId').value));renderEditTags(item?.tags||[])}}render()};
document.querySelector('#deleteTag').onclick=()=>{if(editingTag){const {category,tag}=editingTag;editingTag=null;document.querySelector('#tagModal').hidden=true;deleteTag(category,tag)}};
document.querySelector('#manageTags').onclick=()=>{renderTagManager();document.querySelector('#tagManageModal').hidden=false};
document.querySelector('#closeTagManageModal').onclick=()=>document.querySelector('#tagManageModal').hidden=true;
document.querySelector('#tagManageList').onclick=e=>{const button=e.target.closest('[data-tag-action]');if(!button)return;const {category,tag,tagAction}=button.dataset;if(tagAction==='delete')return deleteTag(category,tag);document.querySelector('#tagManageModal').hidden=true;openTagEditor(category,tag)};

let draggedCategory='';
const categoryOptions=document.querySelector('#categoryOptions');
categoryOptions.addEventListener('change',e=>{if(e.target.name==='expenseCategory')renderExpenseTags([...document.querySelectorAll('input[name="expenseTag"]:checked')].map(x=>x.value))});
categoryOptions.addEventListener('dragstart',e=>{const item=e.target.closest('.category-option');if(!item)return;draggedCategory=item.dataset.category;item.classList.add('dragging')});
categoryOptions.addEventListener('dragend',e=>{e.target.closest('.category-option')?.classList.remove('dragging');categoryOptions.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'))});
categoryOptions.addEventListener('dragover',e=>{e.preventDefault();const item=e.target.closest('.category-option');if(item&&item.dataset.category!==draggedCategory)item.classList.add('drag-over')});
categoryOptions.addEventListener('dragleave',e=>e.target.closest('.category-option')?.classList.remove('drag-over'));
function moveCategory(fromName,toName){const from=categoryOrder.indexOf(fromName),to=categoryOrder.indexOf(toName);if(from<0||to<0||from===to)return;categoryOrder.splice(from,1);categoryOrder.splice(to,0,fromName);localStorage.setItem(categoryOrderKey,JSON.stringify(categoryOrder));renderCategories();render()}
categoryOptions.addEventListener('drop',e=>{e.preventDefault();const target=e.target.closest('.category-option');if(!target||!draggedCategory)return;moveCategory(draggedCategory,target.dataset.category);draggedCategory=''});
let touchCategory=null,suppressCategoryClick=false;
categoryOptions.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;const item=e.target.closest('.category-option');if(!item)return;touchCategory={item,name:item.dataset.category,startX:e.clientX,startY:e.clientY,dragging:false,pointerId:e.pointerId};categoryOptions.setPointerCapture?.(e.pointerId)});
categoryOptions.addEventListener('pointermove',e=>{if(!touchCategory||e.pointerId!==touchCategory.pointerId)return;const moved=Math.hypot(e.clientX-touchCategory.startX,e.clientY-touchCategory.startY)>7;if(!touchCategory.dragging&&!moved)return;touchCategory.dragging=true;e.preventDefault();touchCategory.item.classList.add('touch-dragging');const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.category-option');categoryOptions.querySelectorAll('.touch-drag-over').forEach(item=>item.classList.remove('touch-drag-over'));if(target&&target.dataset.category!==touchCategory.name)target.classList.add('touch-drag-over')});
function finishTouchCategory(e){if(!touchCategory||e.pointerId!==touchCategory.pointerId)return;const {item,name,dragging}=touchCategory,target=dragging?document.elementFromPoint(e.clientX,e.clientY)?.closest('.category-option'):null;item.classList.remove('touch-dragging');categoryOptions.querySelectorAll('.touch-drag-over').forEach(option=>option.classList.remove('touch-drag-over'));if(dragging){suppressCategoryClick=true;if(target&&target.dataset.category!==name)moveCategory(name,target.dataset.category);setTimeout(()=>{suppressCategoryClick=false},0)}touchCategory=null}
categoryOptions.addEventListener('pointerup',finishTouchCategory);
categoryOptions.addEventListener('pointercancel',finishTouchCategory);
categoryOptions.addEventListener('click',e=>{if(!suppressCategoryClick)return;e.preventDefault();e.stopPropagation()},true);
document.querySelector('#editCategoryOptions').addEventListener('change',e=>{if(e.target.name==='editExpenseCategory')renderEditTags([...document.querySelectorAll('input[name="editExpenseTag"]:checked')].map(x=>x.value))});

document.querySelector('#expenseAmount').oninput=()=>note();
document.querySelector('#inputCurrency').onchange=()=>note();

function saveExpense(expense){expenses.push({id:Date.now(),...expense});save();document.querySelector('#expenseForm').reset();expenseDate.value=toDateValue(new Date(expense.createdAt));document.querySelector('#inputCurrency').value=travelCurrency;renderCategories();render()}
function manualRateToBase(amount,krwRate){if(pendingExpense.inputCurrency==='KRW')return baseCurrency==='KRW'?amount:roundBase(amount/krwRate);const krwAmount=amount*krwRate,basePerKrw=pendingExpense?.basePerKrw??(rates?.KRW?1/rates.KRW:null);return baseCurrency==='KRW'?roundBase(krwAmount):basePerKrw===null?null:roundBase(krwAmount*basePerKrw)}
function updateManualRatePreview(){}
function liveKrwPreview(expense,krwRate){const source=`${symbols[expense.inputCurrency]}${money(expense.amount,expense.inputCurrency)}`;if(expense.inputCurrency==='KRW'){const target=expense.manualCurrency;return target==='KRW'?source:`${source} → ${symbols[target]}${money(expense.amount/krwRate,target)}`}return `${source} → ₩${money(Math.round(expense.amount*krwRate),'KRW')}`}
async function openRateModal(expense){expense.manualCurrency=expense.inputCurrency==='KRW'?(baseCurrency==='KRW'?travelCurrency:baseCurrency):expense.inputCurrency;pendingExpense=expense;const liveBase=convert(expense.amount,expense.inputCurrency),liveRate=liveBase===null?null:liveBase/expense.amount,cachedKrwRate=expense.inputCurrency==='KRW'?(baseCurrency==='KRW'?(rates?.[travelCurrency]?1/rates[travelCurrency]:null):rates?.KRW):baseCurrency==='KRW'?liveRate:rates?.KRW&&liveRate?liveRate*rates.KRW:null;document.querySelector('#rateModalTitle').textContent=`${expense.inputCurrency} 결제 환율 선택`;document.querySelector('#manualRateLabel').textContent=`1 ${expense.manualCurrency} = KRW`;document.querySelector('#manualRate').value=cachedKrwRate?String(cachedKrwRate):'';document.querySelector('#liveRatePreview').textContent='실시간 환율을 불러오는 중이에요.';document.querySelector('#rateModeLive').checked=true;document.querySelector('#manualRate').disabled=true;document.querySelector('#rateModal').hidden=false;try{const [baseData,krwData]=await Promise.all([fetchWithTimeout(`https://www.currencyexchangetool.com/api/v1/convert?amount=1&from=${expense.inputCurrency}&to=${baseCurrency}&_=${Date.now()}`,5000),fetchWithTimeout(`https://www.currencyexchangetool.com/api/v1/convert?amount=1&from=${expense.manualCurrency}&to=KRW&_=${Date.now()}`,5000)]),baseRate=Number(baseData.rate),krwRate=Number(krwData.rate);if(pendingExpense!==expense||!baseData.success||!krwData.success||!Number.isFinite(baseRate)||!Number.isFinite(krwRate))return;pendingExpense.liveBase=roundBase(expense.amount*baseRate);pendingExpense.liveRate=baseRate;pendingExpense.basePerKrw=baseRate/krwRate;if(baseCurrency==='KRW'&&expense.inputCurrency==='KRW'&&travelCurrency!=='KRW')pendingExpense.liveTravelAmount=expense.amount/krwRate;if(document.querySelector('#rateModeLive').checked)document.querySelector('#manualRate').value=String(krwRate);document.querySelector('#liveRatePreview').textContent=`실시간 · ${liveKrwPreview(expense,krwRate)}`}catch{}}
document.querySelector('#expenseForm').onsubmit=e=>{e.preventDefault();if(!baseCurrency)return openModal();const amount=Number(document.querySelector('#expenseAmount').value),inputCurrency=document.querySelector('#inputCurrency').value,selected=[...document.querySelectorAll('input[name="expenseCategory"]:checked')].map(x=>x.value),tags=[...document.querySelectorAll('input[name="expenseTag"]:checked')].map(x=>x.value),selectedDate=new Date(`${expenseDate.value}T12:00:00`);if(!selected.length)return alert('지출 항목을 하나 이상 선택해 주세요.');const expense={name:document.querySelector('#expenseName').value.trim(),amount,inputCurrency,categories:selected,tags,date:`${selectedDate.getMonth()+1}/${selectedDate.getDate()}`,createdAt:selectedDate.toISOString()};openRateModal(expense)};
document.querySelectorAll('input[name="rateMode"]').forEach(input=>input.onchange=()=>{document.querySelector('#manualRate').disabled=document.querySelector('#rateModeLive').checked});
document.querySelector('#manualRate').oninput=updateManualRatePreview;
document.querySelector('#closeRateModal').onclick=()=>{pendingExpense=null;document.querySelector('#rateModal').hidden=true};
document.querySelector('#rateForm').onsubmit=e=>{e.preventDefault();if(!pendingExpense)return;const isManual=document.querySelector('#rateModeManual').checked,manualRate=Number(document.querySelector('#manualRate').value),baseAmount=isManual?manualRateToBase(pendingExpense.amount,manualRate):pendingExpense.liveBase??convert(pendingExpense.amount,pendingExpense.inputCurrency);if(isManual&&(!Number.isFinite(manualRate)||manualRate<=0))return alert('올바른 환율을 입력해 주세요.');if(baseAmount===null){loadRates();return alert('환율을 불러오는 중이에요. 잠시 후 다시 시도해 주세요.')}const krwAmount=isManual?(pendingExpense.inputCurrency==='KRW'?pendingExpense.amount:Math.round(pendingExpense.amount*manualRate)):undefined,travelAmount=baseCurrency==='KRW'&&pendingExpense.inputCurrency==='KRW'&&travelCurrency!=='KRW'?(isManual?pendingExpense.amount/manualRate:pendingExpense.liveTravelAmount):undefined,liveRateText=baseCurrency==='KRW'&&pendingExpense.inputCurrency==='KRW'?`실시간 · 1 ${pendingExpense.manualCurrency} = ${document.querySelector('#manualRate').value} KRW`:`실시간 · 1 ${pendingExpense.inputCurrency} = ${pendingExpense.liveRate} ${baseCurrency}`;saveExpense({...pendingExpense,inputAmount:pendingExpense.amount,baseAmount,krwAmount,travelAmount,rateDate:isManual?`직접 입력 · 1 ${pendingExpense.manualCurrency} = ${manualRate} KRW`:pendingExpense.liveRate?liveRateText:rateDate,rateType:isManual?'manual':'live'});pendingExpense=null;document.querySelector('#rateModal').hidden=true};

document.querySelector('#expenseList').onclick=e=>{if(e.target.dataset.editId)return openEditExpense(e.target.dataset.editId);if(e.target.dataset.deleteId){expenses=expenses.filter(x=>x.id!==Number(e.target.dataset.deleteId));
save();
render()}};
document.querySelector('#closeEditExpense').onclick=()=>document.querySelector('#editExpenseModal').hidden=true;
document.querySelector('#editExpenseForm').onsubmit=e=>{e.preventDefault();const id=Number(document.querySelector('#editExpenseId').value),amount=Number(document.querySelector('#editExpenseAmount').value),inputCurrency=document.querySelector('#editInputCurrency').value,baseAmount=convert(amount,inputCurrency),selected=[...document.querySelectorAll('input[name="editExpenseCategory"]:checked')].map(x=>x.value),tags=[...document.querySelectorAll('input[name="editExpenseTag"]:checked')].map(x=>x.value),date=new Date(`${document.querySelector('#editExpenseDate').value}T12:00:00`);if(baseAmount===null)return alert('환율을 불러온 뒤 다시 시도해 주세요.');if(!selected.length)return alert('지출 항목을 하나 이상 선택해 주세요.');expenses=expenses.map(x=>x.id===id?{...x,name:document.querySelector('#editExpenseName').value.trim(),inputAmount:amount,inputCurrency,baseAmount,categories:selected,tags,date:`${date.getMonth()+1}/${date.getDate()}`,createdAt:date.toISOString(),rateDate}:x);save();document.querySelector('#editExpenseModal').hidden=true;render()};
document.querySelector('#feedbackForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,status=document.querySelector('#feedbackStatus');status.textContent='전송 중이에요…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw Error();form.reset();status.textContent='소중한 의견을 보내주셔서 감사합니다!'}catch{status.textContent='전송에 실패했어요. 잠시 후 다시 시도해 주세요.'}};
document.querySelector('#clearButton').onclick=()=>{if(expenses.length&&confirm('모든 지출 기록을 삭제할까요?')){expenses=[];
save();
render()}};

renderCategories();
if(!baseCurrency&&!localStorage.getItem(onboardingKey))openModal('initial');
else{render();
loadRates()}
if(baseCurrency)document.querySelector('#graphBase').value=travelCurrency;
document.querySelector('#graphQuote').value='KRW';
loadExchangeGraph();
setInterval(()=>{if(!document.hidden)loadExchangeGraph()},60000);

const pwaInstallPrompt=document.querySelector('#pwaInstallPrompt'),pwaInstallMessage=document.querySelector('#pwaInstallMessage'),pwaInstallButton=document.querySelector('#pwaInstallButton'),pwaInstallDismiss=document.querySelector('#pwaInstallDismiss'),pwaDismissKey='trip-tally-pwa-install-dismissed',pwaStandalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true,pwaUserAgent=window.navigator.userAgent,pwaIsIosSafari=/iPad|iPhone|iPod/.test(pwaUserAgent)&&/Safari/.test(pwaUserAgent)&&!/(CriOS|FxiOS|EdgiOS)/.test(pwaUserAgent);let deferredInstallPrompt;
const hidePwaInstallPrompt=()=>{pwaInstallPrompt.hidden=true};
const showPwaInstallPrompt=(message,canInstall=false)=>{if(pwaStandalone||sessionStorage.getItem(pwaDismissKey))return;pwaInstallMessage.textContent=message;pwaInstallButton.hidden=!canInstall;pwaInstallPrompt.hidden=false};
pwaInstallDismiss.onclick=()=>{sessionStorage.setItem(pwaDismissKey,'1');hidePwaInstallPrompt()};
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;showPwaInstallPrompt('Trip Tally를 홈 화면에 추가해 더 편하게 기록하세요.',true)});
pwaInstallButton.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=undefined;hidePwaInstallPrompt()};
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=undefined;hidePwaInstallPrompt()});
if(pwaIsIosSafari)showPwaInstallPrompt('공유 버튼 → ‘홈 화면에 추가’를 눌러 앱처럼 사용하세요.');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
